#!/bin/sh
### BEGIN INIT INFO
# Provides:          firewall
# Required-Start:    ifupdown 
# Required-Stop:     networking ifupdown
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable iptables firewall.
### END INIT INFO
RULES=`ls  /etc/iptables-firewall-rules* | tail -n 1`


function start_firewall () {
if [ -e "$RULES" ]
then
iptables-restore < $RULES
fi
}
function stop_firewall () {
iptables -P INPUT ACCEPT
iptables -F INPUT
iptables -P OUTPUT ACCEPT
iptables -F OUTPUT
iptables -P FORWARD ACCEPT
iptables -F FORWARD
}

function restart_firewall () {
stop_firewall
start_firewall
}

if [ -x "/sbin/iptables" ] || [ -x "/usr/local/sbin/iptables" ]
then
case "$1" in
start)
start_firewall
;;
stop)
stop_firewall
;;
restart)
restart_firewall
;;
*)
	echo "Usage: firewall {start|stop|restart}"
	exit 1
	;;
esac
else 
echo "firewall not available" 
fi
exit 0
